###############################################################################
# Splunk Enterprise
# File: indexes.conf
# Project: SOC Home Lab
###############################################################################

# ============================================================================
# Default Index
# ============================================================================

[default]
repFactor = auto

# ============================================================================
# Main Index
# ============================================================================

[main]
homePath   = $SPLUNK_DB/main/db
coldPath   = $SPLUNK_DB/main/colddb
thawedPath = $SPLUNK_DB/main/thaweddb

# ============================================================================
# Endpoint Telemetry Index
# ============================================================================

[endpoint]

homePath   = $SPLUNK_DB/endpoint/db
coldPath   = $SPLUNK_DB/endpoint/colddb
thawedPath = $SPLUNK_DB/endpoint/thaweddb

maxDataSize = auto
frozenTimePeriodInSecs = 7776000

###############################################################################
# Windows Index
###############################################################################

[windows]

homePath   = $SPLUNK_DB/windows/db
coldPath   = $SPLUNK_DB/windows/colddb
thawedPath = $SPLUNK_DB/windows/thaweddb

maxDataSize = auto
frozenTimePeriodInSecs = 7776000

###############################################################################
# Sysmon Index
###############################################################################

[sysmon]

homePath   = $SPLUNK_DB/sysmon/db
coldPath   = $SPLUNK_DB/sysmon/colddb
thawedPath = $SPLUNK_DB/sysmon/thaweddb

maxDataSize = auto
frozenTimePeriodInSecs = 7776000

###############################################################################
# Security Events
###############################################################################

[security]

homePath   = $SPLUNK_DB/security/db
coldPath   = $SPLUNK_DB/security/colddb
thawedPath = $SPLUNK_DB/security/thaweddb

maxDataSize = auto
frozenTimePeriodInSecs = 7776000

###############################################################################
# Notes
#
# endpoint  -> Windows endpoint telemetry
# windows   -> Windows Event Logs
# sysmon    -> Sysmon Operational Logs
# security  -> Security Event Logs
#
# Data retention:
# 90 Days
###############################################################################